kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: eliastik/hacklol-modifier
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
      - latest
