expose_php = Off
access.log = /dev/stdout
error_log = /dev/stderr
log_errors = On
display_errors = On
output_buffering = On
error_reporting = E_ALL
session.cookie_httponly = On
session.cookie_samesite = "Strict"