[www]
user = apache
group = apache
listen = 127.0.0.1:9000
 
pm = dynamic
pm.max_children = 50
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 20
pm.max_requests = 500
 
catch_workers_output = yes
decorate_workers_output = no
 
pm.status_path = /phpfpm-server-status

slowlog = /dev/stderr
request_slowlog_timeout = 10s