[unix_http_server]
  file=/run/supervisord/supervisord.sock

[supervisord]
  nodaemon=true
  logfile=/dev/stdout
  pidfile=/run/supervisord/supervisord.pid
  logfile_maxbytes=0

[program:php-fpm]
  command=php-fpm85 -R -F
  stdout_logfile=/dev/stdout
  stdout_logfile_maxbytes=0
  stderr_events_enabled=true
  redirect_stderr=true

[program:httpd]
  command=/bin/sh -c 'if [ -f /etc/apache2/ssl/apache.pem ] && [ -f /etc/apache2/ssl/apache.key ]; then exec /usr/sbin/httpd -D SSL -D FOREGROUND; else exec /usr/sbin/httpd -D FOREGROUND; fi'
  stdout_logfile=/dev/stdout
  stdout_logfile_maxbytes=0
  stderr_logfile=/var/log/apache2/error.log
  stderr_logfile_maxbytes=0

[group:http_server]
  programs=php-fpm,httpd

[rpcinterface:supervisor]
  supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
  serverurl=unix:///run/supervisord/supervisord.sock